### ISSUE TITLE
Code crashes when trying to run.

### ISSUE THREAD

**Issue by mohitsharma0690** [stepjam/ARM#2]
Hi Stephen,

Interesting work!! I was trying to run the launch script and facing some issues with it. Basically, although it runs, it consistently crashes for me during training. I have attached the crash and the VREP crash log below. 

It seems that calling `env.step` from the code results  in PyRep `arms/arm.py` which calls `sim.simGetConfigForTipPose` with an invalid ik-group argument. I manually verified that this value is `2030003` but I am not sure why it is invalid or why this error crops up. I have separately checked my PyRep installation and I can run the example scripts, so I am not really sure what's wrong. 

I would appreciate if you could help me with it.

```
Process train_env0:                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                             
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                                                                                      
    self.run()                                                                                                                                                                                                 
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/multiprocessing/process.py", line 99, in run                                                                                                              
    self._target(*self._args, **self._kwargs)                                                                                                                                                                  
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/yarr/runners/_env_runner.py", line 167, in _run_env                                                                                         
    raise e                                                                                                                                                                                                    
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/yarr/runners/_env_runner.py", line 141, in _run_env                                                                                         
    for replay_transition in generator:                                                                                                                                                                        
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/yarr/utils/rollout_generator.py", line 34, in generator                                                                                     
    transition = env.step(act_result)                                                                                                                                                                          
  File "/home/mohit/ARM/arm/custom_rlbench_env.py", line 114, in step                                                                                                                  
    obs, reward, terminal = self._task.step(action)                                                                                                                                                            
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/rlbench/task_environment.py", line 302, in step              
    list(arm_action), collision_checking=False)                                                                                                                                                                
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/rlbench/task_environment.py", line 199, in _path_action    
    action, collision_checking, relative_to)                                                                                                                                                                   
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/rlbench/task_environment.py", line 146, in _path_action_get_path
    relative_to=relative_to,                                                                                                                                                                                   
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/pyrep/robots/arms/arm.py", line 447, in get_path                                                                                            
    relative_to)                                                                                                                                                                                               
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/pyrep/robots/arms/arm.py", line 390, in get_nonlinear_path                                                                                  
    strings=[algorithm.value])                                                                                                                                                                                 
  File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/pyrep/backend/utils.py", line 67, in script_call                                                                                            
    list(floats), list(strings), bytes)                                                                                                                                                                          File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/pyrep/backend/sim.py", line 702, in simExtCallScriptFunction                                                                                
    _check_return(ret)                                                                                                                                                                                           File "/home/mohit/anaconda3/envs/arm/lib/python3.7/site-packages/pyrep/backend/sim.py", line 32, in _check_return                                                                                            
    'The call failed on the V-REP side. Return value: %d' % ret)                                                                                                                                               
RuntimeError: The call failed on the V-REP side. Return value: -1  
```  

here is the VREP preview which shows the crash log 
![q_attention_code_fail 2021-08-07 15-55-06](https://user-images.githubusercontent.com/1913957/128618916-4976d8f5-f2e4-4592-bd98-af18587ba4dd.png)

**Comment by stepjam** [comment]
Hi,
Thanks for checking out the work!
This looks like a PyRep issue; I *think* this is directly related to a CoppeliaSim-PyRep version mismatch; can you confirm your CoppeliaSim version please?
